/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { MoveName } from './_move_names.js';

export interface MoveCardBetweenShortStacksArgs {
  FromFirst: boolean;
}

export interface MoveCardBetweenDrawAndDiscardStacksArgs {
  FromDraw: boolean;
}

/** Maps move names to their typed argument interfaces. */
export type MoveArgs = {
  "Move Card Between Short Stacks": MoveCardBetweenShortStacksArgs;
  "Move Card Between Draw And Discard Stacks": MoveCardBetweenDrawAndDiscardStacksArgs;
  "Flip Card Between Hidden and Revealed": Record<string, never>;
  "Move Fan Card": Record<string, never>;
  "Visible Shuffle": Record<string, never>;
  "Shuffle": Record<string, never>;
  "Move Between Hidden": Record<string, never>;
  "Move Token": Record<string, never>;
  "Move Token Sanitized": Record<string, never>;
  "Start Move All Components To Hidden": Record<string, never>;
  "Start Move All Components To Visible": Record<string, never>;
  "Shuffle Hidden": Record<string, never>;
};
