/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

export const MoveNames = {
  MoveCardBetweenShortStacks: "Move Card Between Short Stacks",
  MoveCardBetweenDrawAndDiscardStacks: "Move Card Between Draw And Discard Stacks",
  FlipCardBetweenHiddenAndRevealed: "Flip Card Between Hidden and Revealed",
  MoveFanCard: "Move Fan Card",
  VisibleShuffle: "Visible Shuffle",
  Shuffle: "Shuffle",
  MoveBetweenHidden: "Move Between Hidden",
  MoveToken: "Move Token",
  MoveTokenSanitized: "Move Token Sanitized",
  StartMoveAllComponentsToHidden: "Start Move All Components To Hidden",
  StartMoveAllComponentsToVisible: "Start Move All Components To Visible",
  ShuffleHidden: "Shuffle Hidden",
} as const;

export type MoveName = typeof MoveNames[keyof typeof MoveNames];
