/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { CatalogComponent, ExpandedStack, FullGameState } from '../../src/types/boardgame-types.js';

export type PhaseValue = "Normal";

export interface CardsComponentValues {
  readonly Type: string;
}

export interface ComponentCatalog {
  readonly "cards": readonly CatalogComponent<CardsComponentValues>[];
  readonly "tokens": readonly CatalogComponent<Readonly<Record<string, never>>>[];
}

export type DynamicComponentValues = Readonly<Record<string, never>>;

export type GameConstants = Readonly<Record<string, never>>;

export interface GameComputed extends Readonly<Record<string, unknown>> {}

export interface PlayerComputed extends Readonly<Record<string, unknown>> {}

export interface GameState {
  readonly AllHiddenStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly AllVisibleStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly Card: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly CurrentPlayer: number;
  readonly DiscardStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly DrawStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly FanDiscard: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly FanShuffleCount: number;
  readonly FanStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly FirstShortStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly HiddenCard: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly HiddenStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly Phase: PhaseValue;
  readonly SanitizedTokensFrom: ExpandedStack<Readonly<Record<string, never>>, Readonly<Record<string, unknown>>>;
  readonly SanitizedTokensTo: ExpandedStack<Readonly<Record<string, never>>, Readonly<Record<string, unknown>>>;
  readonly SecondShortStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly TokensFrom: ExpandedStack<Readonly<Record<string, never>>, Readonly<Record<string, unknown>>>;
  readonly TokensTo: ExpandedStack<Readonly<Record<string, never>>, Readonly<Record<string, unknown>>>;
  readonly VisibleCard: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly VisibleStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly Computed?: GameComputed;
}

export interface PlayerState {
  readonly Hand: ExpandedStack<CardsComponentValues, Readonly<Record<string, unknown>>>;
  readonly PlayerInactive: boolean;
  readonly SeatClosed: boolean;
  readonly SeatFilled: boolean;
  readonly Computed?: PlayerComputed;
}

export type State = FullGameState<GameState, PlayerState, GameComputed, PlayerComputed, DynamicComponentValues>;
