/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { MoveName } from './_move_names.js';

export interface MoveTokenArgs {
  SpaceIndex: string;
  TargetPlayerIndex: number;
  TokenIndexToMove: string;
}

/** Maps move names to their typed argument interfaces. */
export type MoveArgs = {
  "Move Token": MoveTokenArgs;
};
