/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { CatalogComponent, ExpandedStack, FullGameState } from '../../src/types/boardgame-types.js';

export type ColorValue = "Red" | "Black";

export type PhaseValue = "Setup" | "Playing";

export type SpacesValue = "0_0" | "0_1" | "0_2" | "0_3" | "0_4" | "0_5" | "0_6" | "0_7" | "1_0" | "1_1" | "1_2" | "1_3" | "1_4" | "1_5" | "1_6" | "1_7" | "2_0" | "2_1" | "2_2" | "2_3" | "2_4" | "2_5" | "2_6" | "2_7" | "3_0" | "3_1" | "3_2" | "3_3" | "3_4" | "3_5" | "3_6" | "3_7" | "4_0" | "4_1" | "4_2" | "4_3" | "4_4" | "4_5" | "4_6" | "4_7" | "5_0" | "5_1" | "5_2" | "5_3" | "5_4" | "5_5" | "5_6" | "5_7" | "6_0" | "6_1" | "6_2" | "6_3" | "6_4" | "6_5" | "6_6" | "6_7" | "7_0" | "7_1" | "7_2" | "7_3" | "7_4" | "7_5" | "7_6" | "7_7";

export interface TokensComponentValues {
  readonly Color: ColorValue;
}

export interface ComponentCatalog {
  readonly "Tokens": readonly CatalogComponent<TokensComponentValues>[];
}

export interface TokensDynamicComponentValues {
  readonly Crowned: boolean;
}

export interface DynamicComponentValues {
  readonly "Tokens": readonly TokensDynamicComponentValues[];
}

export interface GameConstants {
  readonly "BOARD_SIZE": 64;
}

export interface ComputedEnumOption {
  readonly Key: number;
  readonly Name: string;
  readonly CSSColor?: string;
}

export interface GameComputed {
  readonly PlayerOrder?: readonly number[];
  readonly AvailableTeams?: readonly ComputedEnumOption[];
  readonly AvailableRoles?: readonly ComputedEnumOption[];
  readonly AvailableColors?: readonly ComputedEnumOption[];
  readonly ReadyToStartError?: string;
}

export interface PlayerComputed {
  readonly Color: string;
  readonly MayBeActive: boolean;
  readonly GameScore?: number;
  readonly TeamValue?: string;
  readonly RoleValue?: string;
  readonly ColorValue?: string;
  readonly IsGameAdmin?: boolean;
}

export interface GameState {
  readonly CurrentPlayer: number;
  readonly Phase: PhaseValue;
  readonly Spaces: ExpandedStack<TokensComponentValues, TokensDynamicComponentValues>;
  readonly UnusedTokens: ExpandedStack<TokensComponentValues, TokensDynamicComponentValues>;
  readonly Computed?: GameComputed;
}

export interface PlayerState {
  readonly CapturedTokens: ExpandedStack<TokensComponentValues, TokensDynamicComponentValues>;
  readonly Color: ColorValue;
  readonly FinishedTurn: boolean;
  readonly PlayerInactive: boolean;
  readonly SeatClosed: boolean;
  readonly SeatFilled: boolean;
  readonly Computed?: PlayerComputed;
}

export type State = FullGameState<GameState, PlayerState, GameComputed, PlayerComputed, DynamicComponentValues>;
