/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

export type HideCardsInput = Record<string, never>;

export interface HideCardsResolved {
  readonly TargetPlayerIndex: number;
}

export type HideCardsWire = Record<string, never>;

export interface RevealCardInput {
  readonly CardIndex: number;
}

export interface RevealCardResolved {
  readonly CardIndex: number;
  readonly TargetPlayerIndex: number;
}

export interface RevealCardWire {
  readonly CardIndex: string;
}

/** Maps move names to creator-facing native inputs. */
export type MoveInputs = {
  "Hide Cards": HideCardsInput;
  "Reveal Card": RevealCardInput;
};

/** @deprecated Use MoveInputs. */
export type MoveArgs = MoveInputs;

export type ResolvedMoveInputs = {
  "Hide Cards": HideCardsResolved;
  "Reveal Card": RevealCardResolved;
};

export type MoveWireInputs = {
  "Hide Cards": HideCardsWire;
  "Reveal Card": RevealCardWire;
};

/** Exact finite choice projections keyed by move name. */
export type MoveChoiceProjections = {
  "Reveal Card": {
    readonly field: "CardIndex";
    readonly value: number;
    readonly input: RevealCardInput;
  };
};

export const moveInputSchema = [
  {
    "name": "Hide Cards",
    "fields": [
      {
        "name": "TargetPlayerIndex",
        "wireType": "playerIndex",
        "disposition": "context-owned",
        "codec": "player-index"
      }
    ]
  },
  {
    "name": "Reveal Card",
    "fields": [
      {
        "name": "CardIndex",
        "wireType": "int",
        "disposition": "required",
        "codec": "integer"
      },
      {
        "name": "TargetPlayerIndex",
        "wireType": "playerIndex",
        "disposition": "context-owned",
        "codec": "player-index"
      }
    ]
  }
] as const;

export const moveInputSchemaFingerprint = "sha256:40b6d67e62dbc348c3dcff8b6a3957fa1a6bb4f7eb02c54b2b65f959cf90886b";

export const moveChoiceProjectionSchema = [
  {
    "moveName": "Reveal Card",
    "fieldName": "CardIndex",
    "source": "stack-slots",
    "stackSource": {
      "scope": "game",
      "property": "HiddenCards"
    },
    "disclosure": "actor-exact"
  }
] as const;

export const moveChoiceProjectionSchemaFingerprint = "sha256:5c046960abdccaff37af1d4964959fc340eeb9649ce94e66aa842c25006dcfab";
