/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

export const MoveNames = {
  RevealCard: "Reveal Card",
  HideCards: "Hide Cards",
} as const;

export type MoveName = typeof MoveNames[keyof typeof MoveNames];
