/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { CatalogComponent, ExpandedStack, ExpandedTimer, FullGameState } from '../../src/types/boardgame-types.js';

export interface CardsComponentValues {
  readonly CardSet: string;
  readonly Type: string;
}

export interface ComponentCatalog {
  readonly "cards": readonly CatalogComponent<CardsComponentValues>[];
}

export type DynamicComponentValues = Readonly<Record<string, never>>;

export type GameConstants = Readonly<Record<string, never>>;

export interface GameComputed extends Readonly<Record<string, unknown>> {}

export interface PlayerComputed extends Readonly<Record<string, unknown>> {}

export interface GameState {
  readonly CardSet: string;
  readonly Cards: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly CurrentPlayer: number;
  readonly HiddenCards: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly HideCardsTimer: ExpandedTimer;
  readonly NumCards: number;
  readonly UnusedCards: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly VisibleCards: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly Computed?: GameComputed;
}

export interface PlayerState {
  readonly CardsLeftToReveal: number;
  readonly PlayerInactive: boolean;
  readonly SeatClosed: boolean;
  readonly SeatFilled: boolean;
  readonly WonCards: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly Computed?: PlayerComputed;
}

export type State = FullGameState<GameState, PlayerState, GameComputed, PlayerComputed, DynamicComponentValues>;
