/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { ExpandedStack, ExpandedTimer, FullGameState } from '../../src/types/boardgame-types.js';

export interface CardsComponentValues {
  CardSet: string;
  Type: string;
}

export interface GameState {
  CardSet: string;
  Cards: ExpandedStack<CardsComponentValues>;
  CurrentPlayer: number;
  HiddenCards: ExpandedStack<CardsComponentValues>;
  HideCardsTimer: ExpandedTimer;
  NumCards: number;
  UnusedCards: ExpandedStack<CardsComponentValues>;
  VisibleCards: ExpandedStack<CardsComponentValues>;
  Computed?: Record<string, unknown>;
}

export interface PlayerState {
  CardsLeftToReveal: number;
  PlayerInactive: boolean;
  SeatClosed: boolean;
  SeatFilled: boolean;
  WonCards: ExpandedStack<CardsComponentValues>;
  Computed?: Record<string, unknown>;
}

export type State = FullGameState<GameState, PlayerState>;
