/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import { BoardgameBaseGameRenderer, BoardgameBasePlayerInfoRenderer } from '../../src/client.js';
import {
  moveInputSchema,
  moveInputSchemaFingerprint,
  type MoveInputs,
} from './_move_args.js';
import type { MoveName } from './_move_names.js';
import type {
  ComponentCatalog,
  DynamicComponentValues,
  GameComputed,
  GameState,
  PlayerComputed,
  PlayerState,
  State,
} from './_types.js';

/** Complete compile-time contract for this game's renderer surface. */
export interface GameClientContract {
  readonly State: State;
  readonly GameState: GameState;
  readonly PlayerState: PlayerState;
  readonly GameComputed: GameComputed;
  readonly PlayerComputed: PlayerComputed;
  readonly Components: ComponentCatalog;
  readonly DynamicComponents: DynamicComponentValues;
  readonly MoveName: MoveName;
  readonly MoveInputs: MoveInputs;
  readonly RendererTag:
    | 'boardgame-render-game-pig'
    | 'boardgame-render-game-pig-table'
    | 'boardgame-render-game-pig-hand';
}

/** Extend this class, then register only your concrete renderer element. */
export abstract class GameRenderer extends BoardgameBaseGameRenderer<
  GameClientContract['State'],
  GameClientContract['Components'],
  GameClientContract['MoveName'],
  GameClientContract['MoveInputs']
> {
  protected override readonly moveInputSchema = moveInputSchema;
  protected override readonly moveInputSchemaFingerprint = moveInputSchemaFingerprint;
}

/** Extend this class for a strictly typed player-info renderer. */
export abstract class PlayerInfoRenderer extends BoardgameBasePlayerInfoRenderer<
  GameClientContract['State'],
  GameClientContract['PlayerState']
> {}
