/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import {
  BoardgameBaseGameRenderer,
  BoardgameBasePlayerInfoRenderer,
  BoardgameHandViewBase,
  BoardgameTableViewBase,
} from '../../src/client.js';
import {
  moveInputSchema,
  moveInputSchemaFingerprint,
  type MoveInputs,
} from './_move_args.js';
import type { MoveName } from './_move_names.js';
import type {
  ComponentCatalog,
  DynamicComponentValues,
  GameConstants,
  GameEnums,
  GameComputed,
  GameState,
  PlayerComputed,
  PlayerState,
  State,
} from './_types.js';

/** Complete compile-time contract for this game's renderer surface. */
export interface GameClientContract {
  readonly State: State;
  readonly GameState: GameState;
  readonly PlayerState: PlayerState;
  readonly GameComputed: GameComputed;
  readonly PlayerComputed: PlayerComputed;
  readonly Components: ComponentCatalog;
  readonly DynamicComponents: DynamicComponentValues;
  readonly Constants: GameConstants;
  readonly Enums: GameEnums;
  readonly MoveName: MoveName;
  readonly MoveInputs: MoveInputs;
  readonly RendererTag:
    | 'boardgame-render-game-pig'
    | 'boardgame-render-game-pig-table'
    | 'boardgame-render-game-pig-hand';
}

/** Extend this class, then register only your concrete renderer element. */
export abstract class GameRenderer extends BoardgameBaseGameRenderer<
  GameClientContract['State'],
  GameClientContract['Components'],
  GameClientContract['MoveName'],
  GameClientContract['MoveInputs'],
  GameClientContract['Constants'],
  GameClientContract['Enums']
> {
  protected override readonly moveInputSchema = moveInputSchema;
  protected override readonly moveInputSchemaFingerprint = moveInputSchemaFingerprint;
}

/** Extend this class for the shared-screen companion surface. */
export abstract class TableRenderer extends BoardgameTableViewBase<
  GameClientContract['State'],
  GameClientContract['Components'],
  GameClientContract['MoveName'],
  GameClientContract['MoveInputs'],
  GameClientContract['Constants'],
  GameClientContract['Enums']
> {
  protected override readonly moveInputSchema = moveInputSchema;
  protected override readonly moveInputSchemaFingerprint = moveInputSchemaFingerprint;
}

/** Extend this class for the private per-player companion surface. */
export abstract class HandRenderer extends BoardgameHandViewBase<
  GameClientContract['State'],
  GameClientContract['Components'],
  GameClientContract['MoveName'],
  GameClientContract['MoveInputs'],
  GameClientContract['Constants'],
  GameClientContract['Enums']
> {
  protected override readonly moveInputSchema = moveInputSchema;
  protected override readonly moveInputSchemaFingerprint = moveInputSchemaFingerprint;
}

/** Extend this class for a strictly typed player-info renderer. */
export abstract class PlayerInfoRenderer extends BoardgameBasePlayerInfoRenderer<
  GameClientContract['State'],
  GameClientContract['PlayerState']
> {}

type RendererConstructor<Base extends HTMLElement> = new () => Base;
type AbstractRendererConstructor<Base extends HTMLElement> = abstract new () => Base;

function rendererConstructorName(constructor: object): string {
  const name = (constructor as { readonly name?: unknown }).name;
  return typeof name === 'string' && name ? name : '(anonymous renderer)';
}

function registerRenderer<Base extends HTMLElement>(
  tagName: string,
  surfaceName: string,
  expectedBaseName: string,
  expectedBase: AbstractRendererConstructor<Base>,
  constructor: RendererConstructor<Base>,
): void {
  const constructorName = rendererConstructorName(constructor);
  if (!(constructor.prototype instanceof expectedBase)) {
    throw new Error(
      '[pig] ' + surfaceName + ' renderer ' + constructorName +
      ' must extend the generated ' + expectedBaseName + ' base',
    );
  }
  const existing = customElements.get(tagName);
  if (existing) {
    throw new Error(
      '[pig] cannot register ' + surfaceName + ' renderer ' + constructorName +
      ' as <' + tagName + '>: that tag is already registered by ' + rendererConstructorName(existing),
    );
  }
  customElements.define(tagName, constructor);
}

/** Register the ordinary game surface under its generated exact tag. */
export function registerGameRenderer<T extends RendererConstructor<GameRenderer>>(
  constructor: T,
): void {
  registerRenderer(
    'boardgame-render-game-pig', 'game', 'GameRenderer', GameRenderer, constructor,
  );
}

/** Register the companion shared-screen surface under its generated exact tag. */
export function registerTableRenderer<T extends RendererConstructor<TableRenderer>>(
  constructor: T,
): void {
  registerRenderer(
    'boardgame-render-game-pig-table', 'table', 'TableRenderer', TableRenderer, constructor,
  );
}

/** Register the companion private-player surface under its generated exact tag. */
export function registerHandRenderer<T extends RendererConstructor<HandRenderer>>(
  constructor: T,
): void {
  registerRenderer(
    'boardgame-render-game-pig-hand', 'hand', 'HandRenderer', HandRenderer, constructor,
  );
}

/** Register the player-info surface under its generated exact tag. */
export function registerPlayerInfoRenderer<T extends RendererConstructor<PlayerInfoRenderer>>(
  constructor: T,
): void {
  registerRenderer(
    'boardgame-render-player-info-pig',
    'player info',
    'PlayerInfoRenderer',
    PlayerInfoRenderer,
    constructor,
  );
}
