/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

export interface RollDiceArgs {
  TargetPlayerIndex: number;
}

export interface DoneTurnArgs {
  TargetPlayerIndex: number;
}

/** Maps move names to their typed argument interfaces. */
export type MoveArgs = {
  "Roll Dice": RollDiceArgs;
  "Done Turn": DoneTurnArgs;
};
