/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

export type DoneTurnInput = Record<string, never>;

export interface DoneTurnResolved {
  readonly TargetPlayerIndex: number;
}

export type DoneTurnWire = Record<string, never>;

export type RollDiceInput = Record<string, never>;

export interface RollDiceResolved {
  readonly TargetPlayerIndex: number;
}

export type RollDiceWire = Record<string, never>;

/** Maps move names to creator-facing native inputs. */
export type MoveInputs = {
  "Done Turn": DoneTurnInput;
  "Roll Dice": RollDiceInput;
};

/** @deprecated Use MoveInputs. */
export type MoveArgs = MoveInputs;

export type ResolvedMoveInputs = {
  "Done Turn": DoneTurnResolved;
  "Roll Dice": RollDiceResolved;
};

export type MoveWireInputs = {
  "Done Turn": DoneTurnWire;
  "Roll Dice": RollDiceWire;
};

export type MoveChoiceProjections = Record<never, never>;

export const moveInputSchema = [
  {
    "name": "Done Turn",
    "fields": [
      {
        "name": "TargetPlayerIndex",
        "wireType": "playerIndex",
        "disposition": "context-owned",
        "codec": "player-index"
      }
    ]
  },
  {
    "name": "Roll Dice",
    "fields": [
      {
        "name": "TargetPlayerIndex",
        "wireType": "playerIndex",
        "disposition": "context-owned",
        "codec": "player-index"
      }
    ]
  }
] as const;

export const moveInputSchemaFingerprint = "sha256:0ec111cedc813b28664fe3b7ce66a7c207221066c629a3b05bded873b1fb13c4";

export const moveChoiceProjectionSchema = [] as const;

export const moveChoiceProjectionSchemaFingerprint = "sha256:9b21dcf704aff3206dc8f43f8d608f4eb6c21d41e85aae6b9db83067ef75dd6e";
