/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { CatalogComponent, ExpandedStack, FullGameState } from '../../src/types/boardgame-types.js';

export type GameEnums = Readonly<Record<string, never>>;

export interface DiceComponentValues {
  readonly Faces: readonly number[];
}

export interface ComponentCatalog {
  readonly "dice": readonly CatalogComponent<DiceComponentValues>[];
}

export interface DiceDynamicComponentValues {
  readonly SelectedFace: number;
  readonly Value: number;
}

export interface DynamicComponentValues {
  readonly "dice": readonly DiceDynamicComponentValues[];
}

export type GameConstants = Readonly<Record<string, never>>;

export interface ComputedEnumOption {
  readonly Key: number;
  readonly Name: string;
  readonly CSSColor?: string;
}

export interface GameComputed {
  readonly PlayerOrder?: readonly number[];
  readonly AvailableTeams?: readonly ComputedEnumOption[];
  readonly AvailableRoles?: readonly ComputedEnumOption[];
  readonly AvailableColors?: readonly ComputedEnumOption[];
  readonly ReadyToStartError?: string;
}

export interface PlayerComputed {
  readonly Color: string;
  readonly MayBeActive: boolean;
  readonly GameScore?: number;
  readonly TeamValue?: string;
  readonly RoleValue?: string;
  readonly ColorValue?: string;
  readonly IsGameAdmin?: boolean;
}

export interface GameState {
  readonly CurrentPlayer: number;
  readonly Die: ExpandedStack<DiceComponentValues, DiceDynamicComponentValues>;
  readonly TargetScore: number;
  readonly Computed?: GameComputed;
}

export interface PlayerState {
  readonly DieCounted: boolean;
  readonly Done: boolean;
  readonly Eliminated: boolean;
  readonly PlayerInactive: boolean;
  readonly RoundScore: number;
  readonly Score: number;
  readonly SeatClosed: boolean;
  readonly SeatFilled: boolean;
  readonly Computed?: PlayerComputed;
}

export type State = FullGameState<GameState, PlayerState, GameComputed, PlayerComputed, DynamicComponentValues>;
