/************************************
 *
 * This file contains auto-generated methods to help configure enums.
 * It was generated by autoreader.
 *
 * DO NOT EDIT by hand.
 *
 ************************************/

package checkers

import (
	"github.com/jkomoros/boardgame/enum"
)

var Enums = enum.NewSet()

var PhaseEnum = Enums.MustAdd("Phase", map[int]string{
	PhasePlaying: "Playing",
	PhaseSetup:   "Setup",
})

var ColorEnum = Enums.MustAdd("Color", map[int]string{
	ColorBlack: "Black",
	ColorRed:   "Red",
})
