/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

export interface PlaceTokenInput {
  readonly Slot: number;
}

export interface PlaceTokenResolved {
  readonly Slot: number;
  readonly TargetPlayerIndex: number;
}

export interface PlaceTokenWire {
  readonly Slot: string;
}

/** Maps move names to creator-facing native inputs. */
export type MoveInputs = {
  "Place Token": PlaceTokenInput;
};

/** @deprecated Use MoveInputs. */
export type MoveArgs = MoveInputs;

export type ResolvedMoveInputs = {
  "Place Token": PlaceTokenResolved;
};

export type MoveWireInputs = {
  "Place Token": PlaceTokenWire;
};

export type MoveChoiceProjections = Record<never, never>;

export const moveInputSchema = [
  {
    "name": "Place Token",
    "fields": [
      {
        "name": "Slot",
        "wireType": "int",
        "disposition": "required",
        "codec": "integer"
      },
      {
        "name": "TargetPlayerIndex",
        "wireType": "playerIndex",
        "disposition": "context-owned",
        "codec": "player-index"
      }
    ]
  }
] as const;

export const moveInputSchemaFingerprint = "sha256:56369abb553e1beac46b41a3b8faa57849b1960e4a460e61c27600d5188470dd";

export const moveChoiceProjectionSchema = [] as const;

export const moveChoiceProjectionSchemaFingerprint = "sha256:9b21dcf704aff3206dc8f43f8d608f4eb6c21d41e85aae6b9db83067ef75dd6e";
