/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { ExpandedStack, FullGameState } from '../../src/types/boardgame-types.js';

export type PhaseValue = "Before First Move" | "After First Move";

export interface TokensComponentValues {
  Value: string;
}

export interface GameState {
  CurrentPlayer: number;
  Phase: PhaseValue;
  Slots: ExpandedStack<TokensComponentValues>;
  Computed?: Record<string, unknown>;
}

export interface PlayerState {
  PlayerInactive: boolean;
  SeatClosed: boolean;
  SeatFilled: boolean;
  TokenValue: string;
  TokensToPlaceThisTurn: number;
  UnusedTokens: ExpandedStack<TokensComponentValues>;
  Computed?: Record<string, unknown>;
}

export type State = FullGameState<GameState, PlayerState>;
