/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { CatalogComponent, ExpandedStack, FullGameState } from '../../src/types/boardgame-types.js';

export type PhaseValue = "Before First Move" | "After First Move";

export interface TokensComponentValues {
  readonly Value: string;
}

export interface ComponentCatalog {
  readonly "tokens": readonly CatalogComponent<TokensComponentValues>[];
}

export type DynamicComponentValues = Readonly<Record<string, never>>;

export interface GameConstants {
  readonly "TOTAL_DIM": 9;
}

export interface GameComputed extends Readonly<Record<string, unknown>> {}

export interface PlayerComputed extends Readonly<Record<string, unknown>> {}

export interface GameState {
  readonly CurrentPlayer: number;
  readonly Phase: PhaseValue;
  readonly Slots: ExpandedStack<TokensComponentValues, Readonly<Record<string, never>>>;
  readonly Computed?: GameComputed;
}

export interface PlayerState {
  readonly PlayerInactive: boolean;
  readonly SeatClosed: boolean;
  readonly SeatFilled: boolean;
  readonly TokenValue: string;
  readonly TokensToPlaceThisTurn: number;
  readonly UnusedTokens: ExpandedStack<TokensComponentValues, Readonly<Record<string, never>>>;
  readonly Computed?: PlayerComputed;
}

export type State = FullGameState<GameState, PlayerState, GameComputed, PlayerComputed, DynamicComponentValues>;
