/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

export const MoveNames = {
  CurrentPlayerHit: "Current Player Hit",
  CurrentPlayerStand: "Current Player Stand",
} as const;

export type MoveName = typeof MoveNames[keyof typeof MoveNames];
