/*
 * Auto-generated by boardgame-util. DO NOT EDIT.
 */

import type { CatalogComponent, ExpandedStack, FullGameState } from '../../src/types/boardgame-types.js';

export type PhaseValue = "Gathering" | "Initial Deal" | "Normal Play" | "Round Cleanup";

export type RankValue = "Unknown" | "Ace" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" | "10" | "Jack" | "Queen" | "King" | "Joker";

export type SuitValue = "�" | "♠" | "♥" | "♣" | "♦" | "Jokers";

export interface GameEnums {
  readonly "phase": { readonly Values?: Readonly<Record<string, PhaseValue>> };
  readonly "Rank": { readonly Values?: Readonly<Record<string, RankValue>> };
  readonly "Suit": { readonly Values?: Readonly<Record<string, SuitValue>> };
}

export interface CardsComponentValues {
  readonly Rank: RankValue;
  readonly Suit: SuitValue;
}

export interface ComponentCatalog {
  readonly "cards": readonly CatalogComponent<CardsComponentValues>[];
}

export type DynamicComponentValues = Readonly<Record<string, never>>;

export type GameConstants = Readonly<Record<string, never>>;

export interface ComputedEnumOption {
  readonly Key: number;
  readonly Name: string;
  readonly CSSColor?: string;
}

export interface GameComputed {
  readonly PlayerOrder?: readonly number[];
  readonly AvailableTeams?: readonly ComputedEnumOption[];
  readonly AvailableRoles?: readonly ComputedEnumOption[];
  readonly AvailableColors?: readonly ComputedEnumOption[];
  readonly ReadyToStartError?: string;
}

export interface PlayerComputed {
  readonly Color: string;
  readonly MayBeActive: boolean;
  readonly GameScore?: number;
  readonly TeamValue?: string;
  readonly RoleValue?: string;
  readonly ColorValue?: string;
  readonly IsGameAdmin?: boolean;
  readonly "HandValue": number;
}

export interface GameState {
  readonly CurrentPlayer: number;
  readonly DiscardStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly DrawStack: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly MaxRounds: number;
  readonly Phase: PhaseValue;
  readonly RRHasStarted: boolean;
  readonly RRLastPlayer: number;
  readonly RRRoundCount: number;
  readonly RRStarterPlayer: number;
  readonly RoundsCompleted: number;
  readonly UnusedCards: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly Computed?: GameComputed;
}

export interface PlayerState {
  readonly Eliminated: boolean;
  readonly Hand: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly HiddenHand: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly PlayerInactive: boolean;
  readonly Score: number;
  readonly SeatClosed: boolean;
  readonly SeatFilled: boolean;
  readonly Stood: boolean;
  readonly VisibleHand: ExpandedStack<CardsComponentValues, Readonly<Record<string, never>>>;
  readonly Computed?: PlayerComputed;
}

export type State = FullGameState<GameState, PlayerState, GameComputed, PlayerComputed, DynamicComponentValues>;
