/************************************
 *
 * This file contains auto-generated methods to help certain structs
 * implement boardgame.SubState and boardgame.MutableSubState. It was
 * generated by autoreader.
 *
 * DO NOT EDIT by hand.
 *
 ************************************/
package tictactoe

import (
	"github.com/jkomoros/boardgame"
)

// Implementation for playerToken

func (p *playerToken) Reader() boardgame.PropertyReader {
	return boardgame.DefaultReader(p)
}

// Implementation for MovePlaceToken

func (M *MovePlaceToken) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(M)
}

// Implementation for MoveAdvancePlayer

func (M *MoveAdvancePlayer) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(M)
}

// Implementation for gameState

func (g *gameState) Reader() boardgame.PropertyReader {
	return boardgame.DefaultReader(g)
}

func (g *gameState) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(g)
}

// Implementation for playerState

func (p *playerState) Reader() boardgame.PropertyReader {
	return boardgame.DefaultReader(p)
}

func (p *playerState) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(p)
}
