/************************************
 *
 * This file contains auto-generated methods to help certain structs
 * implement boardgame.SubState and boardgame.MutableSubState. It was
 * generated by autoreader.
 *
 * DO NOT EDIT by hand.
 *
 ************************************/
package blackjack

import (
	"github.com/jkomoros/boardgame"
)

// Implementation for MoveShuffleDiscardToDraw

func (M *MoveShuffleDiscardToDraw) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(M)
}

// Implementation for MoveAdvanceNextPlayer

func (M *MoveAdvanceNextPlayer) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(M)
}

// Implementation for MoveDealInitialCard

func (M *MoveDealInitialCard) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(M)
}

// Implementation for MoveRevealHiddenCard

func (M *MoveRevealHiddenCard) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(M)
}

// Implementation for MoveCurrentPlayerHit

func (M *MoveCurrentPlayerHit) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(M)
}

// Implementation for MoveCurrentPlayerStand

func (M *MoveCurrentPlayerStand) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(M)
}

// Implementation for gameState

func (g *gameState) Reader() boardgame.PropertyReader {
	return boardgame.DefaultReader(g)
}

func (g *gameState) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(g)
}

// Implementation for playerState

func (p *playerState) Reader() boardgame.PropertyReader {
	return boardgame.DefaultReader(p)
}

func (p *playerState) ReadSetter() boardgame.PropertyReadSetter {
	return boardgame.DefaultReadSetter(p)
}
